/**
 ******************************************************************************
 * @file           : main.cpp
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <iostream>
#include <stdio.h>
#include "adc.hpp"
#include "uart.hpp"

typedef uint32_t ui32;

void delay(volatile ui32 count)
{
    while(count--);
}

int main(void)
{
	// Initialize debug UART
	uart_init();

	int nline = 0;
//	while (true) {
//		const char *msg = "Hello from STM32F411RE\r\n";
//		for (int i = 0; msg[i] != '\0'; i++) {
//			uart_write(msg[i]);
//		}
//		delay(1200000);
//	}

	while (true) {
		const char *msg = "Hello from STM32F411RE #0";

		// Send text
		for (int i = 0; msg[i] != '\0'; i++) {
			uart_write(msg[i]);
		}

		// Convert num to text then send
		int temp = nline;

		if (temp == 0) {
			uart_write('0');
		}
		else {
			char digits[10];
			int i = 0;

			while (temp > 0) {
				// convert to ASCII
				digits[i++] = (temp % 10) + '0';
				temp /= 10;
			}

			// send in correct order
			while (i--) {
				uart_write(digits[i]);
			}
		}

		// New line
		uart_write('\r');
		uart_write('\n');

		nline++;
		delay(2000000);
	}
}
