/**
 ******************************************************************************
 * @file           : main.cpp
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <iostream>
#include <stdio.h>
#include "adc.hpp"
#include "uart.hpp"

typedef uint32_t ui32;

void delay(volatile ui32 count)
{
    while(count--);
}

int main(void)
{
	// Initialize debug UART
	uart_init();
	pal_adc_init();
	start_conversation();

	while (true) {
		ui32 adc_value = adc_read(); 	// 0-4095
		ui32 pwm_ = (adc_value * 1000) / 4095;


		// TIM2 – Canal 1 (CH1)
		TIM2->CCR1 = pwm_;

		printf("ADC: %lu | PWM: %lu\r\n", adc_value, pwm_);
		uart_write('j');
		delay(500000);
	}

}
