/**
 ******************************************************************************
 * @file           : main.cpp
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * Siguiendo class 4 20 05 25
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <iostream>
#include <stdio.h>
#include "adc.hpp"
#include "uart.hpp"

typedef uint32_t ui32;
typedef uint8_t ui8;

// bit_word_addr = bit_band_base + (byte_offset x 32) + (bit_number × 4)
#define BIT_WORD_ADDRES_SRAM(address, bit) (SRAM1_BB_BASE + ((address - SRAM_BASE) * 32)+ (bit *4))
#define BIT_WORD_ADDRES_PP(address, bit) (PERIPH_BB_BASE + ((address - PERIPH_BASE) * 32) + (bit * 4))
#define GPIOA_PA5_ODR *((volatile ui8 *)BIT_WORD_ADDRES_PP(0x40020014, 5))

void _delay(volatile ui32 count)
{
    while(count--);
}



int main(void)
{
	uart_init();
	// *((volatile ui32 *)(0x20000300)) |= 1 << 2;
	// *((volatile ui32 *)(0x22006008))  = 0;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	// Mode pin work
	GPIOA->MODER &= ~(GPIO_MODER_MODE5);
	GPIOA->MODER |=   GPIO_MODER_MODE5_0;

	std::string msg = "Hello from STM32F411RE!";
	std::string msg_bye = "Bye!";

	while (true) {
		GPIOA_PA5_ODR = 1;

		uart_write_nbyte('\n');
		for (const char& c : msg) {
			uart_write_nbyte(c);
		}
		uart_write_nbyte('\r');
		uart_write_nbyte('\n');
		_delay(5000000);

		GPIOA_PA5_ODR = 0;

		uart_write_string(msg_bye.c_str());  // use std::string
		uart_write_nbyte('\r');
		uart_write_nbyte('\n');
		_delay(500000);

		GPIOA_PA5_ODR = 1;

		uart_write("Good morning!\r\n"); // use Template<>
		_delay(900000);
	}

}
