/**
 ******************************************************************************
 * @file           : main.cpp
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * This program works trying to implement the ADC periphe with UART February 5 26
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <iostream>
#include <stdio.h>
#include "adc.hpp"
#include "uart.hpp"
#include "pwm.hpp"

typedef uint32_t ui32;
typedef uint8_t ui8;

// bit_word_addr = bit_band_base + (byte_offset x 32) + (bit_number × 4)
#define BIT_WORD_ADDRES_SRAM(address, bit) (SRAM1_BB_BASE + ((address - SRAM_BASE) * 32)+ (bit *4))
#define BIT_WORD_ADDRES_PP(address, bit) (PERIPH_BB_BASE + ((address - PERIPH_BASE) * 32) + (bit * 4))
#define GPIOA_PA5_ODR *((volatile ui8 *)BIT_WORD_ADDRES_PP(0x40020014, 5))

void _delay(volatile ui32 count)
{
    while(count--);
}

int main(void)
{

	// Init ADC
	pal_adc_init();
	start_conversation();

	// Init UART
	uart_init();

	// Init PWM
	pwm_init();
	pwm_timer_init();
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	// Mode pin work
	GPIOA->MODER &= ~(GPIO_MODER_MODE5);
	GPIOA->MODER |=   GPIO_MODER_MODE5_0;

	char buffer[10];

	std::string msg = "Hello from STM32F411RE!";
	std::string msg_bye = "Bye!";

	uart_write("\nGood morning! \r\n\n");

	while (true) {
		ui32 adc_value = adc_read(); // 0 - 4095
		// Change ADC to range of PWM (ARR = 1000)
		ui32 pwm_value = (adc_value * 1000) / 4095;
		// Change Duty Cycle
		TIM2->CCR1 = pwm_value;

		// memset(buffer, 0, sizeof(buffer));
		snprintf(buffer, sizeof(buffer), "%lu", static_cast<unsigned long>(pwm_value));
		uart_write_string(buffer);
		uart_write_nbyte('\r');
		uart_write_nbyte('\n');
		_delay(910000);
	}

}
